### ISSUE TITLE
Add Ansible support

### ISSUE THREAD

**Issue by MikeHorn-git** [thalesgroup-cert/FAST#1]
[Ansible](https://github.com/ansible/ansible) playbook for Ubuntu.
Using [Cast](https://github.com/ekristen/cast) for installing REMnux and SIFT. SIFT CLI is [deprecated](https://github.com/teamdfir/sift-cli?tab=readme-ov-file#deprecation-note-this-project-will-be-deprecated-on-march-1-2023-it-is-being-replace-with-cast-which-is-a-single-smaller-binary-capable-of-installing-any-cast-compatible-distribution-such-as-sift-or-remnux-and-more-soon).
Lint with [ansible-lint](https://github.com/ansible/ansible-lint).
Ansible allow to support easier, other Linux distros in the future.

```yml
---
- name: FAST - Ubuntu
  hosts: localhost
  become: true
  connection: local

  tasks:
    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: true

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Install Autopsy
      ansible.builtin.apt:
        name: autopsy
        state: present

    - name: Download CyberChef
      ansible.builtin.get_url:
        url: "https://gchq.github.io/CyberChef/CyberChef_v10.18.6.zip"
        dest: "/tmp/CyberChef_v10.18.6.zip"
        mode: '0644'

    - name: Create CyberChef directory on Desktop
      ansible.builtin.file:
        path: "/home/{{ lookup('env', 'SUDO_USER') }}/Desktop/CyberChef"
        state: directory
        mode: '0755'

    - name: Unzip CyberChef to Desktop/CyberChef
      ansible.builtin.unarchive:
        src: "/tmp/CyberChef_v10.18.6.zip"
        dest: "/home/{{ lookup('env', 'SUDO_USER') }}/Desktop/CyberChef"
        remote_src: true

    - name: Remove CyberChef zip file
      ansible.builtin.file:
        path: "/tmp/CyberChef_v10.18.6.zip"
        state: absent

    - name: Install Free Hex Editor (GHex)
      ansible.builtin.apt:
        name: ghex
        state: present

    - name: Install Wireshark
      ansible.builtin.apt:
        name: wireshark
        state: present

    - name: Download cast
      ansible.builtin.get_url:
        url: "https://github.com/ekristen/cast/releases/download/v0.14.30/cast-v0.14.30-linux-amd64.deb"
        dest: "/tmp/cast-v0.14.30-linux-amd64.deb"
        mode: '0644'

    - name: Install cast
      ansible.builtin.apt:
        deb: "/tmp/cast-v0.14.30-linux-amd64.deb"
        state: present

    - name: Set permissions for cast
      ansible.builtin.file:
        path: /usr/bin/cast
        mode: '0755'
      become: true
```
Install with :
```bash
sudo ansible-playbook Ubuntu.yml
```
